let STEPS_DATA = [ {
        id: 1,
        title: "Préparations & imprévus",
        date: "Mardi 12/10/21",
        text: "Vérifications techniques en présence de nos familles au Château de Lastours (Portel des corbières) de 14h à 19h Verre de l’amitié au Château de Lastours de 19h à 20h qu’on a manqué pour aller chercher un rétro tout neuf à Roberto (el 4x4), resté dans la main d’Angelique.Un grand merci à Pierre de Perpignan notre sauveur! Remise des dons à la Croix Rouge, apparemment tous les équipages ont été plus que généreux… les camions étaient trop petits.",
        pictures: [ 'photo_car_kiss.jpg' ],
        picturesMobile: [ 'photo_car_kiss-mobile.jpg' ],
    },
    {
        id: 2,
        title: "Début de la croisière",
        date: "Mercredi 13/10/21",
        text: "Vérifications administratives manquées la veille vous savez pourquoi…au Château de Lastours de 07h à 11h puis départ de l’événement donné vers 11h. Une ambiance de folie et déjà beaucoup d’émotions. RDV au port de Sète à 14h00 pour l'embarquement avec nos 2 sponsors Paradiform et YBYParis qui nous ont encouragées jusqu’au bout avec l’envie de se planquer dans la voiture. 18h montée dans le bateau.<br>La croisière commence, découverrte de notre cabine de luxe de 4m2 sans fenêtre avec une mention spéciale pour la douche/toilettes/lavabo. On espère juste que le capitaine n’est pas celui du Costa Concordia",
        pictures: [ 'photo_titanic.jpg' ],
        picturesMobile: [ 'photo_titanic-mobile.jpg' ],
    },
    {
        id: 3,
        title: "Petit bateau sur l’eau...",
        date: "Jeudi 14/10/21",
        text: "Journée rencontres avec d’autres équipages, coaching usage du matériel vidéo… c’est pas gagné avec un ordi pourri et une Go Pro dernière génération.<br><br>Travail du road book 1 étape de liaison Nador - Errachidia. Avec la carte du Maroc c’est plutôt simple. Avec la boussole ce sera une autre histoire !",
        pictures: [ 'in_boat.jpg' ],
        picturesMobile: [ 'in_boat-mobile.jpg' ],
    },
    {
        id: 4,
        title: "Arrivée à Nador, on prend la route !",
        date: "Vendredi 15/10/21",
        text: "Sortie du bateau sans accident dans une joyeuse anarchie Arrivée du bateau à Nador...<br><br>Étape de liaison aujourd’hui jusqu’au Bivouac. Départ de Nador, road book à la main, route N19 direction Taourirt.",
        pictures: [ 'direction_taourirt2.jpg' ],
        picturesMobile: [ 'direction_taourirt2-mobile.jpg' ],
    },
    {
        id: 5,
        title: "Hassi Berhane, Gorge du Ziz & lac d’Errachidia",
        date: "Vendredi 15/10/21",
        text: "Passage d’un village Hassi Berkhane (étape liaison).<br>Direction Guercif.<br>Les Gorges du Ziz.<br>Descente sur le lac d’Errachidia.",
        pictures: [ 'gorge_ziz1.jpg', 'gorge_ziz2.jpg' ],
        picturesMobile: [ 'gorge_ziz1-mobile.jpg', 'gorge_ziz2-mobile.jpg' ],
    },
    {
        id: 6,
        title: "Bivouac sous le ciel étoilé",
        date: "Vendredi 15/10/21",
        text: "Bilan première étape de liaison : Mentions spéciales aux Gorges du Ziz. Une route incroyable, de nombreux villages traversés avec des encouragements de tous côtés.<br><br>Ce soir choix de notre petit nid douillet… un bivouac magnifique sous un ciel étoilé. Une douche bien méritée ! Et un excellent repas au coin du feu. Présentation de l’étape du samedi... ça promet! Le Big Warm Up comme en GP.",
        pictures: [ 'bivouac1.jpg', 'bivouac2.jpg', 'bivouac3.jpg', 'bivouac4.jpg' ],
        picturesMobile: [ 'bivouac1-mobile.jpg', 'bivouac2-mobile.jpg', 'bivouac3-mobile.jpg', 'bivouac4-mobile.jpg' ],
    },
    {
        id: 7,
        title: "The Big Warm Up",
        date: "Samedi 16/10/21",
        text: "Un lever de soleil de dingue! Spéciale navigation le matin que de la piste et des obstacles tout à la boussole puis une étape de liaison jusqu’à Merzouga. Big warm up done ! Sans encombre ! Sans s’ensabler Roberto a assuré et les pilotes également.<br><br>Très fatiguant et besoin de beaucoup de vigilance pour piloter sur ces terrains accidents : pierriers, sable mou, trous et marches, traversée d’oueds. Une navigation parfois piégeuse qui a fait douté Ornella. Heureusement nous sommes 2 pilotes et navigatrices dans l’âme. <br>NB: Ornella est priée d’avoir une conduite moins sportive dans le sable",
        pictures: [ 'photo_big_warmup.jpg' ],
        picturesMobile: [ 'photo_big_warmup-mobile.jpg' ],
    },
    {
        id: 8,
        title: "The Big Warm Up (suite)",
        date: "Samedi 16/10/21",
        text: "Cet après-midi après avoir déchargé les dons, c’est opération préparation des kits d’hygiène pour l’association enfants du désert. Superbe élan de solidarité et de travail à la chaîne pour tout dépoter et refaire des lots même en pleine chaleur.<br>Et le soir surprise du chef pour les 20 ans : une étape d’orientation de 13 km de nuit. Intitulée Verdict : no problemo ! Rentrées à 22h repas douche froide… grosse journée qui apparemment est facile par rapport à demain.",
        pictures: [ 'photo_big_warmup2.jpg' ],
        picturesMobile: [ 'photo_big_warmup2-mobile.jpg' ],
    },
    {
        id: 9,
        title: "28ème au classement!",
        date: "Dimanche 17/10/21",
        text: "Nous sommes arrivées 28ème au classement sur 130! On savoure cette victoire étant donné que ce n’était pas du tout fait exprès. Étape du jour : spéciale Wonder Woman ! Une étape à ne pas prendre avec des pincettes… le road book a de moins en moins d’indications, de plus en plus de check points à valider. 8h de conduite sans les arrêts. 153km à parcourir.<br>Les paysages étaient époustouflants : des plateaux immenses rocheux et noirs, des oasis au milieu de nulle part, et des dînettes pour terminer. Une étape qui a nécessité beaucoup de rigueur en navigation et en pilotage car des pièges, un sable bien mou, des km d’oueds. La course est une épreuve de stratégie : les meilleures trajectoires, les caps les plus justes, les coupes intelligentes avec la prise de risque bien calculée.",
        pictures: [ 'classement1.jpg', 'classement2.jpg', 'classement3.jpg', 'classement4.jpg'],
        picturesMobile: [ 'classement1-mobile.jpg', 'classement2-mobile.jpg', 'classement3-mobile.jpg', 'classement4-mobile.jpg'],
    },{
        id: 10,
        title: "28ème au classement! (suite)",
        date: "Dimanche 17/10/21",
        text: "On a pu voir que l’organisation maîtrisait bien son sujet : mécanique, hélicoptère pour les secours… pas de blessées heureusement. La prudence était de mise et nous devons ménager Roberto, en prendre soin pour aller au bout du rallye et le ramener chez lui !<br>Bilan : une très belle course, une erreur de navigation qui va peser au classement mais tellement fières de notre capacité respective à alterner conduite/navigation en toute confiance et toujours dans la bonne humeur. NB : Ornella a comparé la prise de décision de savoir comment passer une dune à celle d’avoir un enfant. Angélique en rit encore.",
        pictures: [ 'classement5.jpg', 'classement6.jpg', 'classement7.jpg' ],
        picturesMobile: [ 'classement5-mobile.jpg', 'classement6-mobile.jpg', 'classement7-mobile.jpg' ],
    },
    {
        id: 11,
        title: "21 ème au classement !",
        date: "Lundi 18/10/21",
        text: "Ce matin c’était la présentation du Club des petits déjeuners pendant le ptit dej. Une association canadienne qui fait de la sensibilisation pour les enfants qui fautes de moyens partent le ventre vide le matin.<br>Départ pour une étape de plus de 140km avec beaucoup de plateaux désertiques de toutes les couleurs.<br>Premier ensablage mais léger ce matin dans un oued très sablonneux. Pelles, plaques de desensablage : un échauffement avant les dunes demain ! On commence à se prendre au jeu : coupes de trajectoire, hors-piste, à chaque check-point notre cri d d’la victoire du jour Tintintîn tintin Chiwawa spéciale dédicace à (Lou) Begaa.<br>Angélique a trouvé l’amour avec Camel le dromadaire et Ornella a joué les Mike avec un colson pour aider un équipage qui avait cassé une pièce.",
        pictures: [ 'step9-1.jpg', 'step9-2.jpg', 'step9-3.jpg', 'step9-4.jpg', 'step9-5.jpg', 'step9-6.jpg', 'step9-7.jpg', 'step9-8.jpg' ],
        picturesMobile: [ 'step9-1-mobile.jpg', 'step9-2-mobile.jpg', 'step9-3-mobile.jpg', 'step9-4-mobile.jpg', 'step9-5-mobile.jpg', 'step9-6-mobile.jpg', 'step9-7-mobile.jpg', 'step9-8-mobile.jpg' ],
    },
    {
        id: 12,
        title: "L’ERG CHEBI",
        date: "Mardi 19/10/21",
        text: "WHO RUN THE DUNES ! GIRLS ! Ce matin grand moment d’émotions avec l’association Ruban Rose pour la fameuse photo dans le désert aux couleurs de la lutte contre le cancer du sein. On a beaucoup pensé à des personnes proches de nous dans ce moment-là. Un mot simple d’ordre préventif : l’auto palpation ! Puis l’étape des Dunes… en pleine après-midi sous 45deg comment vous dire… les pelles et les plaques de desensablages n’ont plus de secret !",
        pictures: [ 'chebi1.jpg', 'chebi2.jpg' ],
        picturesMobile: [ 'chebi1-mobile.jpg', 'chebi2-mobile.jpg' ],
    },
    {
        id: 13,
        title: "l’ERG CHEBI (suite)",
        date: "Mardi 19/10/21",
        text: "Épreuve difficile pour nous : beaucoup d’équipages tankés qui vous font vous ensabler, Roberto a été soumis à rude épreuve… il a trop chauffé donc on a dû nettoyer le radiateur avec la soufflette et laisser le liquide de refroidissement qui était en ébullition redescendre en température, redegonfler plusieurs fois les pneus.<br>Côté sensations : fortes et fun, fières d’avoir franchi cette étape redoutable à la force des bras et du mental<br>NB 1 : toujours s’écouter et surtout les bons conseils de Claude Monpays<br>NB 2 : Angélique a été magnifique dans une descente de l’extrême un mur de sable. Ornella trop impressionnée!<br>NB 3 : Ornella s’est révélée être une slalomeuse des sables. Roberto et nous sommes sains et saufs sans casse et trop contents d’avoir vécu cette expérience.",
        pictures: [ 'chebi3.jpg' ],
        picturesMobile: [ 'chebi3-mobile.jpg' ],
    },
    {
        id: 14,
        title: "MARATHON WOMAN : the ultimatum",
        date: "Mercredi 20/10/21",
        text: "Jour 1 de l’étape finale : 347 km à faire en 2j et en totale autonomie sans assistance ni ravitaillement. Nuit en campement avant le coucher du soleil.<br>On a beaucoup roulé pour essayer de faire la moitié. On s’est donné rendez-vous avec d’autres roses pour faire un petit campement sympa.<br>On a coupé stratégiquement et on est à moins 700 m de l’objectif. On se prend au jeu de plus en plus mais parfois on perd.<br>Nous avons traversé des plateaux sur des km, arides, des lacs desséchés, en mode MAD  MAX.",
        pictures: [ 'marathon-women1.jpg', 'marathon-women2.jpg', 'marathon-women3.jpg'],
        picturesMobile: [ 'marathon-women1-mobile.jpg', 'marathon-women2-mobile.jpg', 'marathon-women3-mobile.jpg'],
    },
    {
        id: 15,
        title: "MARATHON WOMAN : the ultimatum (suite)",
        date: "Mercredi 20/10/21",
        text: "Cette immensité est tellement rare… ce sont des paysages bruts.<br>La course est intense dans tout : physiquement, mentalement, dans les rencontres, le vécu, les sensations, la beauté des paysages.<br>Nous avons eu un magnifique coucher de soleil, feu de camp avec des herbes à chameaux, menu : partage de confit de canard, raclette, ration militaire lol (et oui tout le monde en a mangé).<br>Gros fous rires, des partages bref un moment inoubliable<br>NB1: on a dormi en zone blanche donc l’organisation était pas tranquille ça craignait rien.<br>NB2: Ornella a dormi comme un bb même avant Angélique !",
        pictures: [ 'marathon-women4.jpg', 'marathon-women5.jpg'],
        picturesMobile: [ 'marathon-women4-mobile.jpg', 'marathon-women5-mobile.jpg'],
    },
    {
        id: 16,
        title: "Finale du marathon : il nous plus de la moitié…",
        date: "Jeudi 21/10/21",
        text: "Départ au lever du soleil extra. Des caps difficiles avec un souci de piste tracée par erreur qui a planté tout le monde. Beaucoup de pierres avec risque de crevaison… merci la formation car aucun souci pour nous marche, dévers, Roberto passe partout<br>Un oued gigantesque sablonneux où il y a beaucoup de tankages qu’Angelique a traversé de manière plus qu’habile<br>De très grandes distances à maintenir au cap… pas facile.",
        pictures: [ 'finale-marathon1.jpg', 'finale-marathon2.jpg', 'finale-marathon3.jpg', 'finale-marathon4.jpg'],
        picturesMobile: [ 'finale-marathon1-mobile.jpg', 'finale-marathon2-mobile.jpg', 'finale-marathon3-mobile.jpg', 'finale-marathon4-mobile.jpg'],
    },
    {
        id: 17,
        title: "Finale du marathon (suite)",
        date: "Jeudi 21/10/21",
        text: "Des paysages toujours aussi beaux et diversifiés<br>Petite étape : inscription des noms dans le désert pour nos soutiens ;-)<br>Ornella a fini par tracer en fin de  journée en dépassant tout le monde.<br>Arrivée au son des darboukas, photos, félicitations de tout le monde. We did it!!! Ce soir on est 28ème au classement 4x4 et 39ème tous véhicules confondus<br>Une douche très appréciée après es 2j…<br>NB1: le matin lever du soleil quel cadeau !! Ornella avait une herbe à chameau en guise de coiffure et Angélique un palmier… on fait local<br>NB2: grosse soirée ce soir et c’est pas la soirée de clôture lol",
        pictures: [ 'soiree-marathon1.jpg', 'soiree-marathon2.jpg', 'soiree-marathon3.jpg'],
        picturesMobile: [ 'soiree-marathon1-mobile.jpg', 'soiree-marathon2-mobile.jpg', 'soiree-marathon3-mobile.jpg'],
    },
    {
        id: 18,
        title: "Soirée de clôture à Boulajoul",
        date: "Vendredi 22/10/21",
        text: "On est 33 eme au classement en catégorie 4x4 sur 130 et 43 eme toutes catégories sur 155. Un grand merci à vous tous familles, amis, collègues, sponsors pour votre soutien !! Nous sommes fières du résultat, l’objectif est atteint !<br>Roberto nous a emmené au bout et que de plaisir et de belles rencontres durant ces 7 jours. On a fait face à nous-mêmes dans les moments difficiles et notre réussite ça a été d’être toujours là l’une pour l’autre, de savoir prendre le relais, de partager les bons résultats comme les tankages !<br>Suite au prochain épisode des AM’n’Roses !",
        pictures: [ 'final1.jpg', 'final2.jpg', 'final3.jpg'],
        picturesMobile: [ 'final1-mobile.jpg', 'final2-mobile.jpg', 'final3-mobile.jpg'],
    },
    {
        id: 19,
        title: "Retour à bon port!",
        date: "Lundi 25/10/21",
        text: "Débarquement au Port de Sète à 9h le temps de se dire au-revoir avec les autres roses, séquence émotions… Direction Balaruc pour récupérer les affaires d’Ornella et faire un petit bisou aux parents d’Angélique et son fils Elias. Nous reprenons la route direction Prépa 23 à Crocq. On retrouve vite nos marques sur l’autoroute… où sont les dromadaires ? Toute cette verdure ! Et les camions sont chargés normalement ici…<br>Fin de journée : Roberto retrouve ses propriétaires. Il va bien après un rapide check-up. Petite nostalgie face à ce trio d’enfer… Dernières photos souvenirs, Gabriel et Laura des étoiles plein les yeux, des retrouvailles en famille bien méritées. Mais l’aventure ne s'arrête pas là car nous avons gardé des surprises : les off du rallye !",
        pictures: [ 'retour1.jpg', 'retour2.jpg', 'retour3.jpg' ],
        picturesMobile: [ 'retour1-mobile.jpg', 'retour2-mobile.jpg', 'retour3-mobile.jpg' ],
    }
];